// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: emulator_controller.proto
package android.emulation.control

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import com.squareup.wire.WireRpc

interface EmulatorControllerClient : Service {
  @WireRpc(
    path = "/android.emulation.control.EmulatorController/getScreenshot",
    requestAdapter = "android.emulation.control.ImageFormat#ADAPTER",
    responseAdapter = "android.emulation.control.Image#ADAPTER"
  )
  fun getScreenshot(): GrpcCall<ImageFormat, Image>
}
